FROM nvcr.io/nvidia/pytorch:19.10-py3

RUN apt-get update && apt-get install -y emacs
RUN apt-get update && apt-get install sudo
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install cython; pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
RUN `pip install 'git+https://github.com/facebookresearch/fvcore'`
RUN pip install -r requirements.txt

ENV PYTHONPATH=$PYTHONPATH:/workspace/my_tools
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID runuser-group
RUN useradd --create-home -N -l -u $UID -g runuser-group -G sudo --shell /bin/bash runuser
RUN echo runuser:newpassword | chpasswd
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=8.0"
#RUN chown -R runuser:$(id -gn runuser) /home/runuser/.config
