_BASE_: "../Base-RCNN-FPN-APD.yaml"
MODEL:
  ROI_HEADS:
    NAME: "StandardROIHeads"  #  "StandardROIHeads", "MultiROIHeadsAPD"
    NUM_CLASSES: 60
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATASETS:
  TRAIN: ("d2s_train",)
  TEST: ("d2s_val",)
#cfg.MODEL.RPN.BBOX_REG_LOSS_TYPE = "smooth_l1"
#cfg.MODEL.ROI_BOX_HEAD.BBOX_REG_LOSS_TYPE = "smooth_l1"

