_BASE_: "../Base-RCNN-FPN-APD.yaml"
MODEL:
  ROI_MASK_HEAD:
    REINIT_MASK_HEAD: False
    N_MASKS_PER_ROI: 2
  ROI_HEADS:
    NAME: "MultiROIHeadsAPD"  #  "StandardROIHeads", "MultiROIHeadsAPD"
    NUM_CLASSES: 80
  RESNETS:
    DEPTH: 50
SOLVER:
  BASE_LR: 0.05
  STEPS: (210000, 250000)
  MAX_ITER: 5000
  IMS_PER_BATCH: 1
DATASETS:
  TRAIN: ("single_image",)
  TEST: ("single_image",)
DATALOADER:
  SAMPLER_TRAIN: "TrainingSampler"
TEST:
  EVAL_PERIOD: 100
  EXPONENTIAL_CHECKPOINT_SAVE: True
  CONSERVATIVE_CHECKPOINT_CLEAN: False
SEED: 41
