_BASE_: "../Base-RCNN-FPN-APD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  ROI_MASK_HEAD:
    INIT_ACTIVATED_MASK_HEAD: "standard"
    N_MASKS_PER_ROI: 2
  ROI_HEADS:
    NAME: "MultiROIHeadsAPD"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
