_BASE_: "../Base-RCNN-FPN-APD.yaml"
MODEL:
  ROI_MASK_HEAD:
    INIT_ACTIVATED_MASK_HEAD: "custom"  # "standard", "custom"
    N_MASKS_PER_ROI: 2  # only relevant if using the custom mask head
    MATCHING_LOSS: True
  ROI_HEADS:
    NAME: "MultiROIHeadsAPD"  #  "StandardROIHeads", "MultiROIHeadsAPD"
    NUM_CLASSES: 80
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATASETS:
  TRAIN: ("d2s_train",)
  TEST: ("d2s_val",)
#cfg.MODEL.RPN.BBOX_REG_LOSS_TYPE = "smooth_l1"
#cfg.MODEL.ROI_BOX_HEAD.BBOX_REG_LOSS_TYPE = "smooth_l1"
