# [('DATALOADER', 'REPEAT_THRESHOLD'),
#  ('MODEL', 'ROI_MASK_HEAD', 'MATCHING_LOSS'),
#  ('MODEL', 'WEIGHTS'),
#  ('SOLVER', 'BASE_LR'),
#  ('SOLVER', 'IMS_PER_BATCH'),
#  ('SOLVER', 'MAX_ITER')]

# manual_cfg_keys = [
#     ['SOLVER', 'IMS_PER_BATCH'],
#     ['SOLVER', 'BASE_LR'],
#     ['DATALOADER', 'REPEAT_THRESHOLD'],
#     ['MODEL','ROI_HEADS', 'NAME'],
#     ['MODEL','ROI_MASK_HEAD', 'INIT_ACTIVATED_MASK_HEAD'],
#     ['MODEL', 'ROI_MASK_HEAD', 'MATCHING_LOSS']
# ]
