_BASE_: "./base.yaml"
MODEL:
  ROI_HEADS:
    NAME: "MultiROIHeadsAPD"
  ROI_MASK_HEAD:
    INIT_ACTIVATED_MASK_HEAD: "custom"
    N_MASKS_PER_ROI: 2
    MATCHING_LOSS: True
DATALOADER:
  SAMPLER_TRAIN: "GeneralizedRepeatFactorTrainingSampler"
  FILE_FOR_REPEAT_FACTOR: "output/cache/coco_stats/boxmask_intersections.npy"
  REPEAT_THRESHOLD: 0.01
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.1
