_BASE_: "./base.yaml"
MODEL:
  ROI_HEADS:
    NAME: "StandardROIHeads"
DATALOADER:
  SAMPLER_TRAIN: "GeneralizedRepeatFactorTrainingSampler"
  FILE_FOR_REPEAT_FACTOR: "output/cache/coco_stats/boxmask_intersections.npy"
  REPEAT_THRESHOLD: 0.1
